services:
  django: &django
    env_file:
      - ./.envs/.staging/.django
      - ./.envs/.production/.postgres

  traefik:
    env_file:
      - ./.envs/.staging/.traefik

  celeryworker: *django

  celerybeat: *django

  awscli:
    env_file:
      - ./.envs/.staging/.django
